every seconds:
    if {true} is "true":
        wait 1 second
        set {prix.coin.2} to {prix.coin}

command /gui:
    trigger:
        close player's inventory 
        wait 2 ticks
        open chest with 5 rows named "Coin's Gui" to player 
        wait 2 ticks
        format slot 11 of player with 1 sand named "%{prix.coin}%" to be unstealable
        format slot 12 of player with 1 sand named "%{prix.coin.2}%" to be unstealable