command /playerinfo:
    trigger:
        set {money1} to player's balance 
        set {username} to player's name
        send "&eNom : %{username}%"
        send "&eNom : %{money1}%" 

 # ----------------------------------------------------------------

on command "sk reload":
    broadcast "un skript a été reload"

 # ----------------------------------------------------------------

command /opfree:
    trigger:
        op the player
        send "%player% tu es op mageule"

    

