command /text [<text>]:
    trigger:
        send "&dJe sucehite l'air !" to player

# ----------------------------------------------

command /text1 [<text>]:
    trigger:
        send "%arg-1%" to player

# ----------------------------------------------

command /text2 [<text>]:
    trigger:
        if arg-1 = "on":
            send "&aon" to player
        else if arg-1 = "off":
            send "&coff" to player
        else:
            send "try &aonér or &coff" to player
