command /text [<text>]:
    trigger:
        send "&dJe sucehite l'air !" to player

# ----------------------------------------------

command /text1 [<text>]:
    trigger:
        send "%arg-1%" to player

# ----------------------------------------------

command...
    trigger:
        if ... = "on":
            send "..." to ...
        else if arg-1 = "...":
            send "..." to player
        else:
            send "..." to ...
